(function(){
    window.PAGE_DATA = {
  "mcms": {
    "rfq.fm.dialog.text": {
      "rfq.fm.dialog.text.ifm_leads_btnText": "Submit",
      "rfq.fm.dialog.text.cnfm_leads_afterSubmit_des": "Submit information to verify and refresh the page after verification",
      "rfq.fm.dialog.text.ifm_leads_successTit1_nopublish": "Submitted!",
      "rfq.fm.dialog.text.ifm_leads_des": "Currently, the free RFQ trial activity is only open to some free members. Members must submit company-related information and pass our phone review.",
      "rfq.fm.dialog.text.ifm_leads_upgradeBtnDesc": "Would you like to contact our consulting specialists directly?",
      "rfq.fm.dialog.text.ifm_leads_nopublishBtnText": "Chat with consultant",
      "rfq.fm.dialog.text.cnfm_upgrade_title": "Sorry, you have no quotation rights at present",
      "rfq.fm.dialog.text.ifm_leads_successTit2": "We will review your materials and confirm the application result with you by phone within 5 working days.",
      "rfq.fm.dialog.text.cnfm_leads_title": "Get 10 free RFQ quotations immediately\n",
      "rfq.fm.dialog.text.rfq-leads-description": "Receive more business opportunities by accessing free RFQs. There\u2019s a limited quota for selected customers only!",
      "rfq.fm.dialog.text.ifm_leads_successTit1": "We have received your application",
      "rfq.fm.dialog.text.rfq-leads-button-text": "Get Free RFQs",
      "rfq.fm.dialog.text.cnfm_upgrade_btnLink": "https://supplier.alibaba.com/apply/m.htm?code=20018&joinSource=",
      "rfq.fm.dialog.text.ifm_update_btnChatLink": "https://gcx.alibaba.com/icbu/angel/portal.htm?spm=a272f.13537905.k5lttchy.1.48e67e1epIoS8R&pageId=377958&_param_digest_=57f582a264032236fe16f9f2cc72a8a5",
      "rfq.fm.dialog.text.cnfm_leads_afterSubmit_bottomLinkText": "Upgrade to Gold Supplier",
      "rfq.fm.dialog.text.cnfm_leads_titleDesViewMore": "View More",
      "rfq.fm.dialog.text.ifm_leads_defaultErrorMsg": "System error",
      "rfq.fm.dialog.text.cnfm_leads_titleDesViewMoreLink": "https://activity.alibaba.com/rfq/joinSupplier.html?tracelog=rfq#li1",
      "rfq.fm.dialog.text.ifm_update_title": "Sorry, you've no quotation rights at present",
      "rfq.fm.dialog.text.ifm_update_upgradeBtnText": "Upgrade Now",
      "rfq.fm.dialog.text.cnfm_leads_afterSubmit_auth": "Click Here for Verification",
      "rfq.fm.dialog.text.cnfm_upgrade_des": "Only gold suppliers have RFQ. Upgrade now and get unlimited RFQ.",
      "rfq.fm.dialog.text.ifm_leads_successDesc": "Description",
      "rfq.fm.dialog.text.ifm_leads_nopublishLink": "https://ai.alimebot.alibaba.com/intl/index.htm?from=AnppgS8f6l",
      "rfq.fm.dialog.text.cnfm_leads_afterSubmit_btnRefresh": "Submitted and Refresh the Page",
      "rfq.fm.dialog.text.cnfm_leads_authLink": "https://mysourcing.alibaba.com/rfq/auth/enterprise_info_auth.htm",
      "rfq.fm.dialog.text.cnfm_leads_step1": "Apply",
      "rfq.fm.dialog.text.rfq-update-description": "Only Gold Suppliers can receive access to quotations. Please upgrade online to gain access to millions of buyers",
      "rfq.fm.dialog.text.cnfm_leads_afterSubmit_title": "Verify Information Submitted",
      "rfq.fm.dialog.text.ifm_update_btnChatlocale": "Chat with Consultant",
      "rfq.fm.dialog.text.cnfm_leads_step2": "Verify Information Online",
      "rfq.fm.dialog.text.cnfm_leads_step3": "Get RFQ rights",
      "rfq.fm.dialog.text.ifm_leads_descLink": "https://seller.alibaba.com/pricing?spm=a272f.14659327.9947047970.10.3bc35380Vgq2or",
      "rfq.fm.dialog.text.cnfm_leads_titleDes": "Verify company information to get RFQ rights",
      "rfq.fm.dialog.text.cnfm_leads_bottomLinkTextUrl": "https://supplier.alibaba.com/apply/m.htm?code=20018&joinSource=",
      "rfq.fm.dialog.text.cnfm_leads_btnRefreshLink": "https://sourcing.alibaba.com/?tracelog=ma_rfq_verify",
      "rfq.fm.dialog.text.ifm_update_des": "Only gold medal suppliers have quotation permissions, please upgrade to obtain permissions.",
      "rfq.fm.dialog.text.ifm_leads_title": "Get Free RFQs after upgrading to Golden Supplier",
      "rfq.fm.dialog.text.ifm_update_upgradeLink": "https://seller.alibaba.com/ggs/en-US/newProductLanding.html?tracelog=",
      "rfq.fm.dialog.text.ifm_leads_upgradeLink": "https://seller.alibaba.com/ggs/en-US/newProductLanding.html?tracelog=",
      "rfq.fm.dialog.text.ifm_leads_descLinkText": "Learn more",
      "rfq.fm.dialog.text.ifm_leads_successDesc_nopublish": "There are no products in your account. You should upgrade to Golden Supplier and post products.\nYou can submit the form and chat with Alibaba.com consultant online for further information.",
      "rfq.fm.dialog.text.cnfm_upgrade_btnText": "Upgrade to Gold Supplier",
      "rfq.fm.dialog.text.cnfm_leads_afterSubmit_bottomTips": "Want to get unlimited RFQ quotations?",
      "rfq.fm.dialog.text.ifm_leads_step2": "Upgrade to Golden Supplier",
      "rfq.fm.dialog.text.ifm_leads_upgradeBtnText": "Upgrade to Gold Supplier",
      "rfq.fm.dialog.text.ifm_leads_step3": "Get free use",
      "rfq.fm.dialog.text.ifm_leads_step1": "Apply",
      "rfq.fm.dialog.text.ifm_leads_desc": "Currently, the RFQ trial is only open to customers who submit an application form and pass Alibaba's review.",
      "rfq.fm.dialog.text.rfq-update-button-text": "Upgrade Now"
    }
  },
  "reqId": "098819cd-0d33-4b1d-bd77-5d6c2727ada2",
  "bucket": "default",
  "pageView": {
    "totalPages": "100",
    "currentPage": "1",
    "totalItems": "2930"
  },
  "index": {
    "tracelog": "sourcing_list",
    "uuid": "dcf059a4-5075-4d15-b0b4-95de3fdb846d",
    "data": [
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1TgmiiroJm7zK6BS1j2kR9iRdV1B497N_1NM-DKuJ-oxRfQnwHpQZ_WZIt2UuCtpL&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1844185417",
        "rfqId": "1844185417",
        "enrRfqId": "ID1TgmiiroJm7zK6BS1j2kR9iRdV1B497N_1NM-DKuJ-oxRfQnwHpQZ_WZIt2UuCtpL",
        "expirationTime": "",
        "subject": "360 Degree Rotating Rotation Loading Stainless Steel Shaft Hardware Hinges Pivot Hinge for Hidden ...",
        "imageUrl": "",
        "description": "Hi,twhat is the size of this product Material:Stainless steel Surface Finishing:Satin Usage:Wooden Door Size:75*18mm/95*20mm/100*258mm/150*30mm Package:OPP Bag for Each Piece Weight Loading:10kg 20kg ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1800",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "Just now",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1TgmiiroJm7zK6BS1j2kR9iRdV1B497N_1NM-DKuJ-oxRfQnwHpQZ_WZIt2UuCtpL",
        "rfqExtraCount": 5,
        "rfqLeftCount": 8,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "typically_replies",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "Udf6736bd7bfb42bf942bd70afec0d2a3e.jpg",
        "buyerName": "Manu Aluvilayil",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733826680000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1Egg0W3RaK1ZHa5sBuDJZJJqgIdoGfZ9PRbHyWX9Gek5Jy9Bodn9-z_K34HYijdCf&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1845727431",
        "rfqId": "1845727431",
        "enrRfqId": "ID1Egg0W3RaK1ZHa5sBuDJZJJqgIdoGfZ9PRbHyWX9Gek5Jy9Bodn9-z_K34HYijdCf",
        "expirationTime": "",
        "subject": "windows 11 pro",
        "imageUrl": "",
        "description": "do you have any offer price in win 11 pro?",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "4",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "11 minutes before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1Egg0W3RaK1ZHa5sBuDJZJJqgIdoGfZ9PRbHyWX9Gek5Jy9Bodn9-z_K34HYijdCf",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "safvan sncuae",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733826086000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1Egg0W3RaK1ZHa5sBuDJZJJXQyBLi_5HKuAGjq9Yjo73VCkqajKQ2UagMbHNXhEHP&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1844272339",
        "rfqId": "1844272339",
        "enrRfqId": "ID1Egg0W3RaK1ZHa5sBuDJZJJXQyBLi_5HKuAGjq9Yjo73VCkqajKQ2UagMbHNXhEHP",
        "expirationTime": "",
        "subject": "DRH300A(Guarded hot plate testing system)Thermal Conductivity Tester",
        "imageUrl": "",
        "description": "can you give me your formal quoatation for this product.We will be using this for Soil investigation. Standard:ASMT C518,ISO8301,GB/T10295 Customized support:OEM Customized support:ODM ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "12 minutes before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1Egg0W3RaK1ZHa5sBuDJZJJXQyBLi_5HKuAGjq9Yjo73VCkqajKQ2UagMbHNXhEHP",
        "rfqExtraCount": 5,
        "rfqLeftCount": 9,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Lorenz Araojo",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733825993000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1QJGlq9SpJK1DKluoowbAxvH8LrZg1-sihA6XSggYGbJzrpskAv1drFwjkO-2jLlA&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1677817294",
        "rfqId": "1677817294",
        "enrRfqId": "ID1QJGlq9SpJK1DKluoowbAxvH8LrZg1-sihA6XSggYGbJzrpskAv1drFwjkO-2jLlA",
        "expirationTime": "",
        "subject": "SCC Concrete testing V-Funnel test apparatus",
        "imageUrl": "",
        "description": "Self-Consolidating Concrete(SCC)1Flow Table with measure eg.500,600mm,700mm BS EN 12350-5/DIN 1048(OPTIONAL:BASE PLATE 900X900MM WITH MEASURE)2J-Ring Test3L-Box Test Apparatus4V-Funnel Apparatus5U ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "33 minutes before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1QJGlq9SpJK1DKluoowbAxvH8LrZg1-sihA6XSggYGbJzrpskAv1drFwjkO-2jLlA",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "R Nivas",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733824772000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1QJGlq9SpJK1DKluoowbAxvB4asgbLzTsILsd2BpV5lUo1vBgV4i0_yHqXFl2sqaJ&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1844272322",
        "rfqId": "1844272322",
        "enrRfqId": "ID1QJGlq9SpJK1DKluoowbAxvB4asgbLzTsILsd2BpV5lUo1vBgV4i0_yHqXFl2sqaJ",
        "expirationTime": "",
        "subject": "100%Original TS16 Robotic Total Station",
        "imageUrl": "",
        "description": "hi thereI'm looking to buy this productim in UAE/Abu Dhabi so if you can send me details of how the procedure will beand what the product contains Customized support:OEM Customized support:ODM ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "33 minutes before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1QJGlq9SpJK1DKluoowbAxvB4asgbLzTsILsd2BpV5lUo1vBgV4i0_yHqXFl2sqaJ",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Hasan Sultanah",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733824758000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1WwQpaPqqvZDA4cFw3uCKFToYxwEJyJaVU4FnBR43B4pORDFaPATYGzDFhMYgd9l9&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1677891160",
        "rfqId": "1677891160",
        "enrRfqId": "ID1WwQpaPqqvZDA4cFw3uCKFToYxwEJyJaVU4FnBR43B4pORDFaPATYGzDFhMYgd9l9",
        "expirationTime": "",
        "subject": "Shoes men",
        "imageUrl": "https://sc04.alicdn.com/kf/A1eb8597b5058478fae746185e2e70c12S.png_140x140.png",
        "description": "I'm looking for Shoes men. Product specifications: Gender:Boy and Girl Lady Women",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "10",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "49 minutes before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1WwQpaPqqvZDA4cFw3uCKFToYxwEJyJaVU4FnBR43B4pORDFaPATYGzDFhMYgd9l9",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": true,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Girly De La Cerna",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733823799000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1WwQpaPqqvZDA4cFw3uCKFXFxRIk8h-zVSTHTt4JXfnD2fEhR8WgEVkCencBNGGVk&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1843958458",
        "rfqId": "1843958458",
        "enrRfqId": "ID1WwQpaPqqvZDA4cFw3uCKFXFxRIk8h-zVSTHTt4JXfnD2fEhR8WgEVkCencBNGGVk",
        "expirationTime": "",
        "subject": "Global Version Original S24+Ultra 16GB+1TB Android Smartphone 7.3 Inch Stylus Support 4g 5g Network ...",
        "imageUrl": "",
        "description": "Hi there!I'm considering purchasing a mobile phone and accessories from your company.Could you please let me know what the warranty period is for these products?Thank you for your time and assistance....",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "59 minutes before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1WwQpaPqqvZDA4cFw3uCKFXFxRIk8h-zVSTHTt4JXfnD2fEhR8WgEVkCencBNGGVk",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Walche Massilien",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733823218000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1yCOb_waaXbhA0p9QiDp86hqXQ4vW8EydhD3BlU7f_6Z-NdYULloMRHL1x1nnpsou&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1677809454",
        "rfqId": "1677809454",
        "enrRfqId": "ID1yCOb_waaXbhA0p9QiDp86hqXQ4vW8EydhD3BlU7f_6Z-NdYULloMRHL1x1nnpsou",
        "expirationTime": "",
        "subject": "MT20N2 Air Circuit Breaker Masterpact ACB 2000A ACB Original and New",
        "imageUrl": "",
        "description": "dear team,i hope you are doing well.i have an inquiry regarding following description:ACB-MASTERPACT-MODEL:MT20N2-2000Aplease send me your official quotation through E-mail and confirm if the device ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "1 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1yCOb_waaXbhA0p9QiDp86hqXQ4vW8EydhD3BlU7f_6Z-NdYULloMRHL1x1nnpsou",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "kayla roy",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733823090000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1yCOb_waaXbhA0p9QiDp86nrtA6wYw0Kt3BfYdQ2sAL-iXpVVGyA3uubQWtS-YXbX&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1843794347",
        "rfqId": "1843794347",
        "enrRfqId": "ID1yCOb_waaXbhA0p9QiDp86nrtA6wYw0Kt3BfYdQ2sAL-iXpVVGyA3uubQWtS-YXbX",
        "expirationTime": "",
        "subject": "24m2 Wood house Outdoor Resort Home Stay Hotel Prefab Tiny Log Cabin on sale",
        "imageUrl": "",
        "description": "Hi We are interested about your pre-fab houses.Please share some details and budgetary pricing?Should be water resistantBest regardsAnto Joseph Product Type:Wooden house Layout Design:Technical ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "20",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "1 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1yCOb_waaXbhA0p9QiDp86nrtA6wYw0Kt3BfYdQ2sAL-iXpVVGyA3uubQWtS-YXbX",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "A FernanJosephdes",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733820155000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1JQ9tc8ts32mpKN_D0vyTuulFBoqRHOaVMT8fdlJFxwVDnDqvyD3PM2cowlfGBfde&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1843958427",
        "rfqId": "1843958427",
        "enrRfqId": "ID1JQ9tc8ts32mpKN_D0vyTuulFBoqRHOaVMT8fdlJFxwVDnDqvyD3PM2cowlfGBfde",
        "expirationTime": "",
        "subject": "GL Stress Relief Kit Gift for Party Classroom Christmas Stocking Sensory Toys for Kids and Adults ...",
        "imageUrl": "",
        "description": "do you make other kind of customised kits Material:Plastic Function:Developing Intelligence Color:As the pictures Description:Fidget Toys Logo:Aceptable Weight:around 800g Usage:Children's Learing ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "100",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "1 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1JQ9tc8ts32mpKN_D0vyTuulFBoqRHOaVMT8fdlJFxwVDnDqvyD3PM2cowlfGBfde",
        "rfqExtraCount": 5,
        "rfqLeftCount": 9,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "zarain uae",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733819924000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1JQ9tc8ts32mpKN_D0vyTukLoHaO1Bk64neu3PZ37TZkV8I_3pl4yEhXWZRVadqlz&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1844185313",
        "rfqId": "1844185313",
        "enrRfqId": "ID1JQ9tc8ts32mpKN_D0vyTukLoHaO1Bk64neu3PZ37TZkV8I_3pl4yEhXWZRVadqlz",
        "expirationTime": "",
        "subject": "Classic Gyro Toy For Children,spinning Top Beyblade Burst Set Child Gift Collecting Toys,Children's ...",
        "imageUrl": "",
        "description": "Hi,I'm interested in this product. OEM&ODM:Accepted Color:Multicolor optional Quality guarantee:12months Feature:Multi-functional Design:Can mix designs Type:Other Classic Toys Material:metal ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "20",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "2 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1JQ9tc8ts32mpKN_D0vyTukLoHaO1Bk64neu3PZ37TZkV8I_3pl4yEhXWZRVadqlz",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Sneha Karkiu",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733818698000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1xvWnb8gr0rheZo_Q8sRrwUKJmQxQa834XomthceNIFYAGlJK6OaR2Dq1iYwVln0r&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1843958403",
        "rfqId": "1843958403",
        "enrRfqId": "ID1xvWnb8gr0rheZo_Q8sRrwUKJmQxQa834XomthceNIFYAGlJK6OaR2Dq1iYwVln0r",
        "expirationTime": "",
        "subject": "50ml 100ml Round CylinderTransparent Spray Glass Perfume Bottle",
        "imageUrl": "https://sc04.alicdn.com/kf/Sf0590257d1f94017a26c9c6466baa37aM.png_140x140.png",
        "description": "Hi there!I'm reaching out because I'm interested in your glass packaging options.I was wondering if you offer custom design services?If so,could you please provide me with more information on the ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "100",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "2 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1xvWnb8gr0rheZo_Q8sRrwUKJmQxQa834XomthceNIFYAGlJK6OaR2Dq1iYwVln0r",
        "rfqExtraCount": 5,
        "rfqLeftCount": 9,
        "haveAnnexes": true,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Acount Checker",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733818035000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1xvWnb8gr0rheZo_Q8sRrwWVtZY1rf_ceJN0mglxGvxxveSdNIFrTpei0ydT-_2LC&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1844185288",
        "rfqId": "1844185288",
        "enrRfqId": "ID1xvWnb8gr0rheZo_Q8sRrwWVtZY1rf_ceJN0mglxGvxxveSdNIFrTpei0ydT-_2LC",
        "expirationTime": "",
        "subject": "Prefab Homes A-Frame houses Triangular Luxury Villas Fast Install Container House Modular ...",
        "imageUrl": "",
        "description": "HIIm interested what options cost is to have it transported to Bucharest Romania.Best,Dan Advantage:Fast install;Waterproof;seismic;Thermal insulation;Sustainability Custom Projects:Color,size,shape,...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "2 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1xvWnb8gr0rheZo_Q8sRrwWVtZY1rf_ceJN0mglxGvxxveSdNIFrTpei0ydT-_2LC",
        "rfqExtraCount": 5,
        "rfqLeftCount": 9,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Dan Mitre",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733817334000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1xvWnb8gr0rheZo_Q8sRrwYANqpU2OR8FZCoOArCj9a7Rp90JgSROBh1JNgMFx-ht&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1844185280",
        "rfqId": "1844185280",
        "enrRfqId": "ID1xvWnb8gr0rheZo_Q8sRrwYANqpU2OR8FZCoOArCj9a7Rp90JgSROBh1JNgMFx-ht",
        "expirationTime": "",
        "subject": "Hot Sell Custom Tote Bag High Quality Sublimation Black Canvas Bag Tote Cheap Wholesale Canvas ...",
        "imageUrl": "https://sc04.alicdn.com/kf/S770e22ef6521429eae5476706d4c08efR.png_140x140.png",
        "description": "We are looking for x50 high quality,square canvas tote bags,to ship to Dubai.Do you ship to Dubai and if so,what is the lead time?Item name 1:canvas bags Item name 2:canvas tote bag ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "50",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "2 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1xvWnb8gr0rheZo_Q8sRrwYANqpU2OR8FZCoOArCj9a7Rp90JgSROBh1JNgMFx-ht",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": true,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Sophie Douglas",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733816159000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1WW68wyLq6jqAj3lJfKMAiqIFt8lktpKhm7rPnwZdAIsoO2cuwF5k0qA2pIKHrllq&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1845727308",
        "rfqId": "1845727308",
        "enrRfqId": "ID1WW68wyLq6jqAj3lJfKMAiqIFt8lktpKhm7rPnwZdAIsoO2cuwF5k0qA2pIKHrllq",
        "expirationTime": "",
        "subject": "Carro De Juguete Boys Xmas Toy Remote Control 4WD 2.4Ghz Double Sided 360 Degree Rotating with ...",
        "imageUrl": "",
        "description": "Hi Dear Team,I want 1000 pcs Of this remote control car could you please tell me irs DDP price?Thank you. Product name:Remote Control Stunt Car Feature:Follow light climbing wall car toy ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1000",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "3 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1WW68wyLq6jqAj3lJfKMAiqIFt8lktpKhm7rPnwZdAIsoO2cuwF5k0qA2pIKHrllq",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Aniqa Ashraf",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733815817000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1WW68wyLq6jqAj3lJfKMAiktM50wY86AUOhWvXqzyWNv4a2mNHMGBGoa8SrKteadP&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1845727306",
        "rfqId": "1845727306",
        "enrRfqId": "ID1WW68wyLq6jqAj3lJfKMAiktM50wY86AUOhWvXqzyWNv4a2mNHMGBGoa8SrKteadP",
        "expirationTime": "",
        "subject": "extraction machine",
        "imageUrl": "",
        "description": "Pvc pipe manufacturing machine with die 1/2&quot;to 8",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Unit/Units",
        "openTimeStr": "3 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1WW68wyLq6jqAj3lJfKMAiktM50wY86AUOhWvXqzyWNv4a2mNHMGBGoa8SrKteadP",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "CLASTAN KUMAR",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733815775000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1l6ObFv_NaxSbke37qETiLPl73FLgEqT9vM4QABSiwGMgB20nsuHtP9BUNQ4Rn3Qi&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1678975142",
        "rfqId": "1678975142",
        "enrRfqId": "ID1l6ObFv_NaxSbke37qETiLPl73FLgEqT9vM4QABSiwGMgB20nsuHtP9BUNQ4Rn3Qi",
        "expirationTime": "",
        "subject": "Bts gift packaging mystery box",
        "imageUrl": "https://sc04.alicdn.com/kf/Aa2e5323c66104e9da39a7ef263b724ebS.jpg_140x140.jpg",
        "description": "I'm looking for Bts gift packaging mystery box. Product specifications: Paper Type:Kraft Paper Printing Handling:Matt Lamination Feature:Disposable OEM service:Accept for bts gift packaging mystery ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "1",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "3 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1l6ObFv_NaxSbke37qETiLPl73FLgEqT9vM4QABSiwGMgB20nsuHtP9BUNQ4Rn3Qi",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": true,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "U28cc58cfb2e34599b9937a45a0315e655.jpg",
        "buyerName": "Said Elssyed",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733815402000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1l6ObFv_NaxSbke37qETiLE3oRup0gJNN2-iZ2kBoZ4o7FbKuFszoBFzeQXV2siF5&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1843958355",
        "rfqId": "1843958355",
        "enrRfqId": "ID1l6ObFv_NaxSbke37qETiLE3oRup0gJNN2-iZ2kBoZ4o7FbKuFszoBFzeQXV2siF5",
        "expirationTime": "",
        "subject": "ZH3132 Matte lipstick 5Pcs set Long-Lasting Waterproof Makeup Cosmetics 5 Colors Matte Lipstick Set ...",
        "imageUrl": "",
        "description": "hi how much lowest can you make this lipstick price",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "500",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "3 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1l6ObFv_NaxSbke37qETiLE3oRup0gJNN2-iZ2kBoZ4o7FbKuFszoBFzeQXV2siF5",
        "rfqExtraCount": 5,
        "rfqLeftCount": 10,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Shifah Khwaja",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733815080000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1HDHpbjTdUKGWa8fsbC1h2wdNBaRddBjrKuvazgM36yOMjLAktPwletW79VXXKn6q&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1845727286",
        "rfqId": "1845727286",
        "enrRfqId": "ID1HDHpbjTdUKGWa8fsbC1h2wdNBaRddBjrKuvazgM36yOMjLAktPwletW79VXXKn6q",
        "expirationTime": "",
        "subject": "Promotional Engraving Logo Ball Pen Shape USB 2.0 flash drive with Laser Pointer",
        "imageUrl": "",
        "description": "Hi,we need this item in our Brand Name&quot;RitchField&quot;,we are looking for 100 to 200 nos.reply me back ASAP. Products Status:Stock Encryption:Yes Material:metal Style:Rectangle Interface Type:USB 2.0 ...",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "200",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "3 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1HDHpbjTdUKGWa8fsbC1h2wdNBaRddBjrKuvazgM36yOMjLAktPwletW79VXXKn6q",
        "rfqExtraCount": 5,
        "rfqLeftCount": 8,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          },
          {
            "tagName": "typically_replies",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "ritchfield me",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733813818000"
      },
      {
        "url": "//sourcing.alibaba.com/rfq_detail.htm?p=ID1HDHpbjTdUKGWa8fsbC1h2ykj0pEO69I9Esz7P0Rz3sFiq2_c567wtQ4sqlYe2g_A&uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d",
        "id": "1844272175",
        "rfqId": "1844272175",
        "enrRfqId": "ID1HDHpbjTdUKGWa8fsbC1h2ykj0pEO69I9Esz7P0Rz3sFiq2_c567wtQ4sqlYe2g_A",
        "expirationTime": "",
        "subject": "brand new or used NetEngine AR600 Series Router AR617VW-LTE4EA 50010479 1*GE COMBO WAN,4*GE LAN,1*...",
        "imageUrl": "",
        "description": "NetEngine AR600 Series Router-AR617VW-LTE4EA",
        "country": "United Arab Emirates",
        "countrySimple": "AE",
        "quantityValue": "",
        "quantityValueUnit": "",
        "quantity": "7",
        "quantityUnit": "Piece/Pieces",
        "openTimeStr": "3 hours before",
        "quoteExtraCount": 0,
        "quoteLeftCount": 0,
        "quoteUrl": "//rfqposting.alibaba.com/quotation/rfq_quotation_post.htm?uuid=dcf059a4-5075-4d15-b0b4-95de3fdb846d&enc_r_id=ID1HDHpbjTdUKGWa8fsbC1h2ykj0pEO69I9Esz7P0Rz3sFiq2_c567wtQ4sqlYe2g_A",
        "rfqExtraCount": 5,
        "rfqLeftCount": 8,
        "haveAnnexes": false,
        "hasQuoEquity": true,
        "rfqStarLevel": 2,
        "rfqStarMax": 3,
        "rfqTags": [],
        "tags": [
          {
            "tagName": "RFQ_MKT_ST_28101",
            "type": "rfq_level",
            "scene": "default"
          },
          {
            "tagName": "complete_order_via_rfq",
            "type": "buyer",
            "scene": "default"
          },
          {
            "tagName": "emailConfirm",
            "type": "buyer",
            "scene": "default"
          },
          {
            "tagName": "typically_replies",
            "type": "buyer",
            "scene": "default"
          }
        ],
        "hasRead": false,
        "zeroQuoExpiredDate": "",
        "formPurposeCountry": "",
        "orderValue": "",
        "orderValueUnit": "",
        "formPurposeCountryName": "",
        "industryDisplayAttrs": [],
        "portraitPath": "",
        "buyerName": "Ajith Georgeu",
        "qualityScore": "",
        "scoreProfile": [],
        "quoteFirstTimecount": "",
        "quotesDiscount": "",
        "quotesOrigin": "",
        "rfqLevel": "",
        "buyerLevel": "",
        "buyerLevelFlag": "",
        "buyerLevelLogoUrl": "",
        "searchEngineScore": "1733813130000"
      }
    ]
  },
  "scoreMcms": {}
};
})();