name: Run Selenium Scraper

on:
  schedule:
    - cron: '50 12 * * *' # Runs daily at 12:50 PM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7' # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Main1/requirements.txt # Ensure the path to requirements.txt is correct

      # Step 4: Run the Selenium scraper script
      - name: Run scraper
        working-directory: Main1 # Change working directory to Main1
        run: |
          python main.py

      # Step 5: Upload output CSV as an artifact
      - name: Upload CSV output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: govind-csv-output
          path: Main1/Govind.csv # Ensure the path to the generated CSV file is correct
